---
# tasks file for arillso.mariadb

- name: "{{ ansible_distribution | lower }} | add repository"
  yum_repository:
    name: MariaDB
    description: MariaDB repository
    baseurl: "http://yum.mariadb.org/{{ mariadb_version }}/{{ ansible_distribution|lower|regex_replace('redhat', 'rhel') }}{{ ansible_distribution_major_version }}-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
  tags:
    - packages
